language: python

python:
  - "3.4"
  - "3.5"

install:
  pip install coveralls coverage==4.1b2 dill

script:
  - rm -f .coverage
  - python3 -m coverage run --branch --concurrency=multiprocessing -p -m unittest discover
  - python3 -m coverage combine || python3 -m coverage combine
  - ls -la

after_success:
  coveralls
