language: python

python:
  - "3.4"
  - "3.5"

install:
  pip install coveralls coverage==4.2b1

script:
  - rm -f .coverage
  - python3 -m coverage run -m unittest discover
  - python3 -m coverage combine

after_success:
  coveralls
