language: python

python:
  - "3.4"
  - "3.5"

install:
  pip install coveralls coverage\<4.0

script:
  - rm .coverage
  - python3 -m coverage run --branch --concurrency=multiprocessing -p -m nitpycker .
  - python3 -m coverage combine

after_success:
  coveralls
